In [122]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('../data/processed/data_without_nulls.csv')

data

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.30
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.40
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.90
7028,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70
7029,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7030,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7031,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60

In [123]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7032 non-null   object
 1   Churn                      7032 non-null   object
 2   customer.gender            7032 non-null   object
 3   customer.SeniorCitizen     7032 non-null   int64
 4   customer.Partner           7032 non-null   object
 5   customer.Dependents        7032 non-null   object
 6   customer.tenure            7032 non-null   int64
 7   phone.PhoneService         7032 non-null   object
 8   phone.MultipleLines        7032 non-null   object
 9   internet.InternetService   7032 non-null   object
 10  internet.OnlineSecurity    7032 non-null   object
 11  internet.OnlineBackup      7032 non-null   object
 12  internet.DeviceProtection  7032 non-null   object
 13  internet.TechSupport       7032 non-null   object
 14  internet.StreamingTV       7032 non-null   object
 15  internet.StreamingMovies   7032 non-null   object
 16  account.Contract           7032 non-null   object
 17  account.PaperlessBilling   7032 non-null   object
 18  account.PaymentMethod      7032 non-null   object
 19  account.Charges.Monthly    7032 non-null   float64
 20  account.Charges.Total      7032 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [124]:
# Standaring all columns
columns_to_drop = ['customerID',
                    'customer.gender',
                    'phone.PhoneService',
                    'phone.MultipleLines',
                    'internet.OnlineBackup',
                    'internet.DeviceProtection',
                    'internet.StreamingTV',
                    'internet.StreamingMovies'
                    ]

columns_to_rename =  {'Churn': 'churn',
                      'customer.SeniorCitizen': 'is_elder',
                      'customer.Partner': 'have_partner',
                      'customer.Dependents': 'have_dependents',
                      'customer.tenure': 'permanence_months',
                      'internet.InternetService': 'type_internet_service',
                      'internet.OnlineSecurity': 'have_online_security',
                      'internet.TechSupport': 'have_tech_support',
                      'account.Contract': 'type_contract',
                      'account.PaperlessBilling': 'electronic_invoice',
                      'account.PaymentMethod': 'payment_method',
                      'account.Charges.Monthly': 'charges_monthly',
                      'account.Charges.Total': 'charges_total'}

columns_to_lower = ['churn', 
                    'have_partner', 
                    'have_dependents', 
                    'type_internet_service', 
                    'have_online_security',
                    'have_tech_support', 
                    'type_contract', 
                    'electronic_invoice',
                    'payment_method' ]

columns_to_0_1 = ['churn',
                  'have_partner',
                  'have_dependents',
                  'have_online_security',
                  'have_tech_support',
                  'electronic_invoice']

# Eliminating columns not necessary
data = data.drop(columns = columns_to_drop, errors = 'ignore')

# Renaming columns
data = data.rename(columns = columns_to_rename)

# Standarizing the data
data[columns_to_lower] = data[columns_to_lower].apply(lambda x: x.str.lower())

data[columns_to_0_1] = data[columns_to_0_1].apply(lambda x: x.map({'yes': 1, 'no': 0, 'no internet service': 0}))

data['type_contract'] = data['type_contract'].map({'one year': 'anual', 'month-to-month': 'monthly'})

data

,churn,is_elder,have_partner,have_dependents,permanence_months,type_internet_service,have_online_security,have_tech_support,type_contract,electronic_invoice,payment_method,charges_monthly,charges_total
0,0,0,1,1,9,dsl,0,1,anual,1,mailed check,65.60,593.30
1,0,0,0,0,9,dsl,0,0,monthly,0,mailed check,59.90,542.40
2,1,0,0,0,4,fiber optic,0,0,monthly,1,electronic check,73.90,280.85
3,1,1,1,0,13,fiber optic,0,0,monthly,1,electronic check,98.00,1237.85
4,1,1,1,0,3,fiber optic,0,1,monthly,1,mailed check,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,0,0,0,13,dsl,1,1,anual,0,mailed check,55.15,742.90
7028,1,0,1,0,22,fiber optic,0,0,monthly,1,electronic check,85.10,1873.70
7029,0,0,0,0,2,dsl,0,0,monthly,1,mailed check,50.30,92.75
7030,0,0,1,1,67,dsl,1,1,NaN,0,mailed check,67.85,4627.65
7031,0,0,1,1,63,dsl,1,0,NaN,0,electronic check,59.00,3707.60

In [125]:
string_cols = ['type_internet_service', 'type_contract', 'payment_method']

for col in string_cols:
    print(f"\n📊 Column(string): {col}")
    print(data[col].value_counts())

📊 Column(string): type_internet_service
type_internet_service
fiber optic    3096
dsl            2416
no             1520
Name: count, dtype: int64

📊 Column(string): type_contract
type_contract
monthly    3875
anual      1472
Name: count, dtype: int64

📊 Column(string): payment_method
payment_method
electronic check             2365
mailed check                 1604
bank transfer (automatic)    1542
credit card (automatic)      1521
Name: count, dtype: int64

In [126]:
binary_cols = ['churn', 'is_elder', 'have_partner', 'have_dependents', 'have_online_security', 'have_tech_support', 'electronic_invoice']


for col in binary_cols:
    print(f"\n📊 Column(binary): {col}")
    print(data[col].value_counts())

📊 Column(binary): churn
churn
0    5163
1    1869
Name: count, dtype: int64

📊 Column(binary): is_elder
is_elder
0    5890
1    1142
Name: count, dtype: int64

📊 Column(binary): have_partner
have_partner
0    3639
1    3393
Name: count, dtype: int64

📊 Column(binary): have_dependents
have_dependents
0    4933
1    2099
Name: count, dtype: int64

📊 Column(binary): have_online_security
have_online_security
0    5017
1    2015
Name: count, dtype: int64

📊 Column(binary): have_tech_support
have_tech_support
0    4992
1    2040
Name: count, dtype: int64

📊 Column(binary): electronic_invoice
electronic_invoice
1    4168
0    2864
Name: count, dtype: int64

In [127]:
data['charge_daily'] = data['charges_monthly'] / 30

data.head()

,churn,is_elder,have_partner,have_dependents,permanence_months,type_internet_service,have_online_security,have_tech_support,type_contract,electronic_invoice,payment_method,charges_monthly,charges_total,charge_daily
0,0,0,1,1,9,dsl,0,1,anual,1,mailed check,65.6,593.30,2.186667
1,0,0,0,0,9,dsl,0,0,monthly,0,mailed check,59.9,542.40,1.996667
2,1,0,0,0,4,fiber optic,0,0,monthly,1,electronic check,73.9,280.85,2.463333
3,1,1,1,0,13,fiber optic,0,0,monthly,1,electronic check,98.0,1237.85,3.266667
4,1,1,1,0,3,fiber optic,0,1,monthly,1,mailed check,83.9,267.40,2.796667

In [128]:
data.to_csv('../data/processed/data_transformed.csv', index = False, sep = ',')